# Generated by Django 2.2.12 on 2020-07-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemsApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoryGems',
            new_name='HistoryDeals',
        ),
    ]
